; DamballahRetro GameInfo - configuration
RomsPath=C:\RetroBat\roms
Title=DAMBALLAHRETRO
Width=720
Height=250
ScrollSpeed=8
TriggerDelaySeconds=3
VisibleSeconds=30
HiddenSeconds=600
PollSeconds=1

; Ombre de l'overlay
; true  = affiche l'ombre
; false = aucune ombre
Shadow=false
